CREATE TABLE RENT (
    id BIGINT PRIMARY KEY,
    game_id BIGINT NOT NULL,
    player_id VARCHAR(255) NOT NULL,
    rent_start TIMESTAMP,
    rent_end TIMESTAMP,
    CONSTRAINT fk_rent_game FOREIGN KEY (game_id) REFERENCES GAME(id),
    CONSTRAINT fk_rent_player FOREIGN KEY (player_id) REFERENCES PLAYER(id)
);

-- Sequence for RENT table
DROP SEQUENCE IF EXISTS RENT_SEQ;
CREATE SEQUENCE RENT_SEQ START WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM RENT) INCREMENT BY 1;